name: Debug Private Repo Cloning

on: [push]

jobs:
  fetch-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3

      - name: Clone Private Repository (Temporarily)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://x-access-token:$GITHUB_TOKEN@github.com/wtsyeda/wtsyeda_private.git private-folder
          echo "🔍 Listing files in private-folder:"
          ls -la private-folder  # List all files for debugging

      - name: Check If sensitive-data.txt Exists
        run: |
          if [ -f private-folder/sensitive-data.txt ]; then
            echo "✅ File exists: private-folder/sensitive-data.txt"
            cat private-folder/sensitive-data.txt
          else
            echo "❌ ERROR: File not found: private-folder/sensitive-data.txt"
            exit 1  # Fail the workflow if the file is missing
          fi
